apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
        - name: gcp-devops-gke
          image: gcr.io/dauntless-gate-423820-c9/gcpdevops:latest
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-prod
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  selector:
    app: gcp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: "LoadBalancer"
